version: '2'
services:
  db:
    image: mysql:latest
    ports:
    - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: stbmanager123!!
      MYSQL_DATABASE: stbmanager
      MYSQL_USER: stbmanager
      MYSQL_PASSWORD: stbmanager123!!